import type { Metadata } from 'next'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://haude-tea.com'

export const metadata: Metadata = {
  // 基本資訊
  title: {
    default: '豪德製茶所 | Haude Tea',
    template: '%s | 豪德製茶所',
  },
  description:
    '傳承三代的製茶工藝，堅持手工採摘、精心烘焙，為您呈現台灣高山茶的純粹風味。阿里山烏龍茶、蜜香紅茶、高山茶專賣。',
  keywords: ['台灣茶', '高山茶', '烏龍茶', '阿里山', '茶葉', '製茶', '豪德製茶所', '茶園體驗'],

  // 網站基本設定
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: '/',
  },

  // manifest (PWA)
  manifest: '/manifest.webmanifest',

  // Open Graph（Facebook、Line 等）
  // og:image is auto-generated by opengraph-image.tsx
  openGraph: {
    title: '豪德製茶所 | Haude Tea',
    description: '傳承三代的製茶工藝，堅持手工採摘、精心烘焙，為您呈現台灣高山茶的純粹風味。',
    url: SITE_URL,
    siteName: '豪德製茶所',
    locale: 'zh_TW',
    type: 'website',
  },

  // Twitter Card
  // twitter:image is auto-generated by opengraph-image.tsx
  twitter: {
    card: 'summary_large_image',
    title: '豪德製茶所 | Haude Tea',
    description: '傳承三代的製茶工藝，堅持手工採摘、精心烘焙',
    creator: '@haudetea',
  },

  // 其他 SEO 設定
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

/**
 * Root layout — required by Next.js App Router.
 *
 * <html> and <body> are rendered by [locale]/layout.tsx so we can set
 * the correct lang attribute from the URL segment.
 * This wrapper just passes children through.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
